#ifndef DDK712_REG_H__
#define DDK712_REG_H__

#define MISC_GRAPH_VIDEO_CTRL 0
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT 18:16
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT_8 0
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT_15 1
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT_16 2
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT_32 3
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT_24 4
#define MISC_GRAPH_VIDEO_CTRL_DATA_FORMAT_8P 5


#endif
