#!/bin/sh
dmesg -c > /dev/null
if [ $# -lt 2 ];then
echo "no g_option come in,use default value"
parm=""
echo "default g_option is $parm"
else
parm=$2
echo "g_option is $parm"
fi
# start to test
insmod ./lynxfb.ko g_option="$parm"
for((a=1;a<=$1;a=a+1))
do
echo 0 > /sys/class/vtconsole/vtcon1/bind
rmmod lynxfb
insmod ./lynxfb.ko g_option="$parm"
echo "loop $a done"
done

